/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompletedBillsRouteImport } from './routes/completed-bills'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PendingBillsRouteImport } from './routes/pending-bills'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as BillsIdRouteImport } from './routes/bills.$id'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedBillsRoute = CompletedBillsRouteImport.update({
  id: '/completed-bills',
  path: '/completed-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingBillsRoute = PendingBillsRouteImport.update({
  id: '/pending-bills',
  path: '/pending-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completed-bills': typeof CompletedBillsRoute
  '/dashboard': typeof DashboardRoute
  '/pending-bills': typeof PendingBillsRoute
  '/bills/$id': typeof BillsIdRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/bills/': typeof BillsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completed-bills': typeof CompletedBillsRoute
  '/dashboard': typeof DashboardRoute
  '/pending-bills': typeof PendingBillsRoute
  '/bills/$id': typeof BillsIdRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/bills': typeof BillsIndexRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completed-bills': typeof CompletedBillsRoute
  '/dashboard': typeof DashboardRoute
  '/pending-bills': typeof PendingBillsRoute
  '/bills/$id': typeof BillsIdRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/bills/': typeof BillsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completed-bills'
    | '/dashboard'
    | '/pending-bills'
    | '/bills/$id'
    | '/companies/$id'
    | '/bills/'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completed-bills'
    | '/dashboard'
    | '/pending-bills'
    | '/bills/$id'
    | '/companies/$id'
    | '/bills'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/completed-bills'
    | '/dashboard'
    | '/pending-bills'
    | '/bills/$id'
    | '/companies/$id'
    | '/bills/'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletedBillsRoute: typeof CompletedBillsRoute
  DashboardRoute: typeof DashboardRoute
  PendingBillsRoute: typeof PendingBillsRoute
  BillsIdRoute: typeof BillsIdRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  BillsIndexRoute: typeof BillsIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed-bills': {
      id: '/completed-bills'
      path: '/completed-bills'
      fullPath: '/completed-bills'
      preLoaderRoute: typeof CompletedBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-bills': {
      id: '/pending-bills'
      path: '/pending-bills'
      fullPath: '/pending-bills'
      preLoaderRoute: typeof PendingBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletedBillsRoute: CompletedBillsRoute,
  DashboardRoute: DashboardRoute,
  PendingBillsRoute: PendingBillsRoute,
  BillsIdRoute: BillsIdRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  BillsIndexRoute: BillsIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
